// <auto-generated />
using System;
using DaVinciGlobal.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DaVinciGlobal.Migrations
{
    [DbContext(typeof(OracleFIAPDbContext))]
    [Migration("20240607050430_Editando")]
    partial class Editando
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaVinciGlobal.Models.DadoTemperatura", b =>
                {
                    b.Property<int>("DadoTemperaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_dado_temperatura");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DadoTemperaturaId"));

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_coleta")
                        .HasAnnotation("DataColeta", "O campo DataColeta é obrigatório");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("vl_temperatura")
                        .HasAnnotation("Temperatura", "O campo Temperatura é obrigatório");

                    b.HasKey("DadoTemperaturaId");

                    b.HasIndex("SensorId");

                    b.ToTable("TB_DV_DADO_TEMPERATURA", (string)null);
                });

            modelBuilder.Entity("DaVinciGlobal.Models.ImagemCoral", b =>
                {
                    b.Property<int>("ImagemCoralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_imagem_coral");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagemCoralId"));

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_caminho_imagem")
                        .HasAnnotation("CaminhoImagem", "O campo CaminhoImagem é obrigatório");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_envio")
                        .HasAnnotation("DataEnvio", "O campo DataEnvio é obrigatório");

                    b.Property<string>("EstadoCoral")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_estado_coral")
                        .HasAnnotation("EstadoCoral", "O campo EstadoCoral é obrigatório");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_localizacao")
                        .HasAnnotation("Localizacao", "O campo Localizacao é obrigatório");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ImagemCoralId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_DV_IMAGEM_CORAL", (string)null);
                });

            modelBuilder.Entity("DaVinciGlobal.Models.Relatorio", b =>
                {
                    b.Property<int>("RelatorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_relatorio");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelatorioId"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_inicio");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_localizacao");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SensorId");

                    b.Property<double?>("TemperaturaMaxima")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("vl_temperatura_maxima");

                    b.Property<double?>("TemperaturaMedia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("vl_temperatura_media");

                    b.Property<double?>("TemperaturaMinima")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("vl_temperatura_minima");

                    b.HasKey("RelatorioId");

                    b.HasIndex("SensorId");

                    b.ToTable("TB_DV_RELATORIO", (string)null);
                });

            modelBuilder.Entity("DaVinciGlobal.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_localizacao")
                        .HasAnnotation("Localizacao", "O campo Localizacao é obrigatório");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SensorId");

                    b.ToTable("TB_DV_SENSOR", (string)null);
                });

            modelBuilder.Entity("DaVinciGlobal.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_email")
                        .HasAnnotation("Email", "O campo Email é obrigatório");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_usuario")
                        .HasAnnotation("Nome", "O campo Nome é obrigatório");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_senha")
                        .HasAnnotation("Senha", "O campo Senha é obrigatório");

                    b.HasKey("UsuarioId");

                    b.ToTable("TB_DV_USUARIO", (string)null);
                });

            modelBuilder.Entity("DaVinciGlobal.Models.DadoTemperatura", b =>
                {
                    b.HasOne("DaVinciGlobal.Models.Sensor", "Sensor")
                        .WithMany("DadosTemperatura")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("DaVinciGlobal.Models.ImagemCoral", b =>
                {
                    b.HasOne("DaVinciGlobal.Models.Usuario", "Usuario")
                        .WithMany("ImagensCorais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DaVinciGlobal.Models.Relatorio", b =>
                {
                    b.HasOne("DaVinciGlobal.Models.Sensor", "Sensor")
                        .WithMany("Relatorios")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("DaVinciGlobal.Models.Sensor", b =>
                {
                    b.Navigation("DadosTemperatura");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("DaVinciGlobal.Models.Usuario", b =>
                {
                    b.Navigation("ImagensCorais");
                });
#pragma warning restore 612, 618
        }
    }
}
